# -*- coding: utf-8 -*-
"""views.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7T0rhT44LNH_z_-nlrzHc1qaRiIEeyx
"""

from django.shortcuts import render
from django.http import HttpResponse

def index(request):
  return HttpResponse("Hello, world.  You're at the usmapp index.")